# conf/llm/default.yaml - Default LLM configuration
provider: "anthropic" # openai, anthropic, qwen
model_name: "claude-3-7-sonnet-20250219"
async_client: false
temperature: 1
top_p: 1.0
min_p: 0.0
top_k: -1
max_tokens: 4096
api_key: "${OPENAI_API_KEY}"
base_url: https://openrouter.ai/api/v1
keep_tool_result: -1
repetition_penalty: 1.0
